name: Fortify Scan

on:
  # 트리거 설정
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  Fortify-AST-Scan:
    runs-on: ubuntu-latest
    # 점검할 소스코드 Check Out 단계.
    steps:
      - name: Check Out Source Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set SCANCENTRAL_JAVA_HOME, restore original JAVA_HOME and PATH
        run: |
          echo "SCANCENTRAL_JAVA_HOME=${{ env.JAVA_HOME }}" >> ${GITHUB_ENV}

      - name: Setup Fortify tools
        uses: fortify/github-action/setup@v1.2.2
        with:
          tool-definitions: https://github.com/fortify/tool-definitions/releases/download/v1/tool-definitions.yaml.zip
          export-path: true
          fcli: skip
          sc-client: 24.2
          vuln-exporter: latest
          bugtracker-utility: skip
          debricked-cli: skip

	  # Fortify Scan Central Client가 잘 설치되었는지 확인합니다.
      # Fortify scancentral 명령어를 통해 Scan Central Client의 버전 확인
      - name: Run scancentral from PATH
        run: scancentral --version

	  # Fortify scancentral.exe가 환경변수에 잘 등록되었는지 Scan Central help 확인
      - name: Run scancentral using SC_CLIENT_CMD environment variable
        run: ${SC_CLIENT_CMD} -h

	  # Fortify SAST Scan을 위한 env 설정 및 Scan 요청 보내기
      - name: Start SAST scan-
        uses: fortify/github-action/internal/run@main
        
        # 요청을 보낼 때 필요한 환경변수를 설정합니다.
        env:
          DO_WAIT: false
          DO_EXPORT: true
          SSC_URL: ${{ secrets.SSC_URL }}
          SC_CONTROLLER_URL: ${{ secrets.SC_CONTROLLER_URL }}
          SSC_TOKEN: ${{ secrets.SSC_TOKEN }}
          SSC_UPLOAD_TOKEN: ${{ secrets.SSC_UPLOAD_TOKEN }}
          
        # 요청 command를 입력합니다.!
        with:
          cmd: '"${SC_CLIENT_CMD}" -url ${SC_CONTROLLER_URL} start -bt none -upload -application "github_action" -version "test1" -uptoken ${SSC_UPLOAD_TOKEN}'
          
