name: Fortify Scan

on:
  # 트리거 설정
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  Fortify-AST-Scan:
    runs-on: ubuntu-latest
    # 점검할 소스코드 Check Out 단계.
    steps:
      - name: Check Out Source Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set SCANCENTRAL_JAVA_HOME, restore original JAVA_HOME and PATH
        run: |
          echo "SCANCENTRAL_JAVA_HOME=${{ env.JAVA_HOME }}" >> ${GITHUB_ENV}

      - name: Setup Fortify tools
        uses: fortify/github-action/setup@v1.2.2
        with:
          tool-definitions: https://github.com/fortify/tool-definitions/releases/download/v1/tool-definitions.yaml.zip
          export-path: true
          fcli: skip
          sc-client: 24.2
          vuln-exporter: latest
          bugtracker-utility: skip
          debricked-cli: skip

      - name: Run scancentral from PATH
        run: scancentral --version

      - name: Run scancentral using SC_CLIENT_CMD environment variable
        run: ${SC_CLIENT_CMD} -h

      - name: Start SAST scan-
        uses: fortify/github-action/internal/run@main

        env:
          DO_WAIT: false
          DO_EXPORT: true
          SSC_URL: ${{ secrets.SSC_URL }}
          SC_CONTROLLER_URL: ${{ secrets.SC_CONTROLLER_URL }}
          SSC_TOKEN: ${{ secrets.SSC_TOKEN }}
          SSC_UPLOAD_TOKEN: ${{ secrets.SSC_UPLOAD_TOKEN }}

        with:
          cmd: '"${SC_CLIENT_CMD}" -url ${SC_CONTROLLER_URL} start -bt none -upload -application "github_action" -version "test1" -uptoken ${SSC_UPLOAD_TOKEN}'
          
